"""Shared human-readable labels for canonical strategy keys."""

from typing import Tuple

STRATEGY_DISPLAY_NAMES: dict[str, Tuple[str, str]] = {
    # C=Classical, E=Exotical
    # Storage strategies
    "dictionary_encoding": ("Dictionary Encoding", "C"),
    "compact_int16_date": ("Frame-of-Reference Date Encoding", "C"),
    "scaled_integer": ("Scaled Integer (Fixed-Point Decimal)", "C"),
    "string_arena": ("Flat String Arena (offset array)", "C"),
    "temporal_sharding_zonemap": ("Date Partitioning + Zone Maps", "C"),
    "join_range_directory": ("Sparse Join-Key Range Index", "C"),
    "join_hash_index": ("Hash Index (O(1) join lookup)", "E"),
    "precomputed_predicate": ("Precomputed Boolean Predicate Flag", "E"),
    "sorted_physical_layout": ("Physical Row Sort Order", "C"),
    "SoA_columnar_layout": ("Columnar Layout (Struct-of-Arrays)", "C"),
    "micro_AoS_pack": ("PAX-Style Hybrid Layout (hot columns)", "C"),
    "precomputed_lookup_table": ("Precomputed Arithmetic Lookup Table", "E"),
    "shipmode_indexed_shard": ("Composite Secondary Index (shard × key)", "C"),
    "per_order_aggregated_flag": ("Per-Group Materialized Summary", "C"),
    "precomputed_derived_column": ("Precomputed Derived Column", "E"),
    "bit_packed_record": ("Bit-Packed Record (sub-byte fields)", "E"),
    "word_presence_bitmask": ("Per-Row Word-Presence Bitmask", "E"),
    "compact_bitset_membership": ("Compact Membership Bitset (1-bit/key)", "E"),
    "inline_csr_payload": ("Inline CSR Payload (values in CSR order)", "E"),
    "prejoined_column": ("Pre-Joined FK-Chain Column", "E"),
    "cached_index_range": ("Cached CSR Range Pair", "E"),
    "compact_nonempty_key_list": ("Compact Non-Empty-Key List", "E"),
    # Execution strategies
    "bitmap_semi_join": ("Bitmap Semi-Join", "E"),
    "index_nested_loop_join": ("Index Nested-Loop Join", "C"),
    "tag_array_join": ("Encoded-Key Join", "E"),
    "hash_join": ("Hash Join", "C"),
    "sort_merge_join": ("Sort-Merge Join", "C"),
    "streaming_group_join": ("Sort-Based Group Aggregation", "E"),
    "full_table_scan": ("Full Table Scan", "C"),
    "shard_skip_scan": ("Shard-Skip Scan (Zone Maps)", "C"),
    "sorted_range_scan": ("Sorted Range Scan", "C"),
    "sorted_key_range_lookup": ("Foreign-Key Range Lookup", "C"),
    "dictionary_predicate_rewrite": ("Dictionary Predicate Rewrite", "E"),
    "precomputed_flag_scan": ("Precomputed Flag Scan", "E"),
    "secondary_index_scan": ("Secondary Index Scan", "E"),
    "direct_array_aggregation": ("Array-Indexed Group Aggregation", "E"),
    "dense_key_aggregation": ("Bounded-Domain Hash Aggregation", "E"),
    "hash_aggregation": ("Hash Aggregation", "C"),
    "scalar_aggregation": ("Scalar Aggregation", "C"),
    "inline_aggregation": ("Pipeline-Fused Aggregation", "E"),
    "two_phase_aggregation": ("Two-Phase Aggregation", "C"),
    "software_prefetching": ("Software Prefetching", "E"),
    "loop_unrolling": ("Manual Loop Unrolling", "E"),
    "branch_hint_optimization": ("Branch-Prediction Hints", "E"),
    "pointer_restrict_scan": ("Pointer __restrict Aliasing", "E"),
    "compiler_target_directives": ("Compiler Target Directives (AVX2)", "E"),
    "lookup_table_arithmetic": ("Lookup-Table Arithmetic", "E"),
    "integer_scaled_arithmetic": ("Integer Scaled Arithmetic", "E"),
    "branchless_range_check": ("Branchless Range Check", "E"),
    "bitmap_substring_test": ("Bitmap Substring Test (word-mask AND)", "E"),
    "memmem_substring_filter": ("memchr/memcmp Substring Filter", "C"),
    "hand_vectorized_simd": ("Hand-Vectorized SIMD Intrinsics", "E"),
    "magic_number_division": ("Magic-Number Division", "E"),
    "parallel_radix_sort": ("Parallel MSD Radix Sort", "E"),
    "pairwise_merge_tree_sort": ("Per-Thread Sort + Pairwise Merge Tree", "E"),
    "scalar_std_sort": ("Single-Threaded std::sort", "C"),
    # Multi-threading strategies (Coordination & Dispatch)
    "pinned_shared_thread_pool": ("Pinned Shared Thread Pool", "C"),
    "hybrid_spin_then_sleep": ("Hybrid Spin-then-Sleep Idle", "E"),
    "zero_alloc_parallel_dispatch": ("Zero-Alloc Parallel Dispatch", "E"),
    "generation_counter_dispatch": ("Generation-Counter Wakeup", "C"),
    # Multi-threading strategies (Work Distribution)
    "row_range_partition": ("Row-Range Partitioning", "C"),
    "key_range_partition": ("Key-Range Partitioning (CSR)", "C"),
    "nonempty_key_list_partition": ("Non-Empty Key List Partitioning", "E"),
    "bitmask_word_partition": ("Bitmask-Word Range Partitioning", "E"),
    "morsel_simd_aligned_partition": ("SIMD-Aligned Morsel Partition", "E"),
    "prefix_sum_load_balancing": ("Prefix-Sum Row-Volume Load Balancing", "E"),
    # Multi-threading strategies (Coordination & Dispatch)
    "per_thread_accumulator_merge": ("Per-Thread Accumulator + Merge", "C"),
    "ownership_partitioning_no_atomics": ("Ownership Partitioning (no atomics)", "C"),
    "relaxed_atomic_aggregation": ("Relaxed-Order Atomic Aggregation", "E"),
    "conditional_atomic_set": ("Load-Then-Conditional Atomic Set", "E"),
    "idempotent_byte_write": ("Idempotent Byte Write (race-safe)", "E"),
    # Multi-threading strategies (Work Distribution)
    "histogram_prefix_scatter": ("Parallel Histogram-Prefix-Scatter", "C"),
    "per_destination_subbuffers": ("Per-Destination Sub-Buffers", "E"),
    "flat_stripe_buffer": ("Flat Stripe Buffer (single alloc)", "E"),
    "magic_constant_stripe_routing": ("Magic-Constant Stripe Routing", "E"),
    # Multi-threading strategies (Memory & Cache)
    "cacheline_padded_accumulators": ("Cache-Line Padded Accumulators", "C"),
    "nontemporal_prefetch_streaming": ("Non-Temporal Prefetch", "E"),
    "hugepage_anonymous_mmap": ("Hugepage Anonymous mmap", "E"),
    "parallel_first_touch_init": ("Parallel First-Touch Init", "E"),
    "pooled_reusable_buffers": ("Pooled Reusable Buffers", "C"),
    # Multi-threading strategies (Loader-Side)
    "parallel_column_extraction": ("Parallel Column Extraction", "C"),
    "parallel_radix_sort_permutation": ("Parallel Radix-Sort Permutation", "E"),
    "concurrent_csr_index_build": ("Concurrent CSR Index Build", "C"),
    "per_table_build_threads": ("Per-Table Build Threads", "C"),
}
